version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: alpine:3.9
        environment:
          ECR_REPOSITORY: <repository>
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: '--dev'
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run pytest 
          name: Test
      - run:
          command: |
            pipenv run pylint ./workoutshare
          name: Lint
workflows:
  main:
    jobs:
      - build