version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/ethereal-machines-backend


    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            cat Pipfile
            pip freeze > requirements.txt
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            python ./workoutshare/manage.py test
      - run:
          name: run lint
          command: pipenv run "pylint .\workoutshare\"

      - store_artifacts:
          path: test-reports
          destination: test-reports