version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/ethereal-machines-backend


    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip install --upgrade pip
            sudo pip install pipenv
            pipenv install
      - run:
          name: run tests
          command: pipenv run "python workoutshare\manage.py test"
      - run:
          name: run lint
          command: pipenv run "pytlin .\workoutshare\"

      - store_artifacts:
          path: test-reports
          destination: test-reports