version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.10
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: workoutshare_admin
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install pipenv
          name: Install pipenv
      - run:
          command: pipenv install
          name: Install dependencies
      - run:
          command: |
            pipenv run pytest 
          name: Test
      - run:
          command: |
            pipenv run pylint ./workoutshare
          name: Lint
workflows:
  main:
    jobs:
      - build
