version: 2.1
jobs:
  build:
    docker:
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: workoutshare_admin
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run pytest 
          name: Test
      - run:
          command: |
            pipenv run pylint ./workoutshare
          name: Lint
workflows:
  main:
    jobs:
      - build