version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run pytest --version
          name: Test
      - run:
          command: |
            pipenv run pylint ./workoutshare
          name: Lint
workflows:
  main:
    jobs:
      - build
