version: 2.1

orbs:
  python: circleci/python@1.2.0
  
workflows:
  main:
    jobs:
      - python/test:
          environment:
            PYTHONPATH: /home/circleci/project/src
          pkg-manager: pip
          test-tool: pytest
