version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10
        environment:
          PIPENV_VENV_IN_PROJECT: true
          PYTHONPATH: /home/circleci/project/src
    working_directory: ~/ethereal-machines-backend


    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            cat Pipfile
            pip freeze > requirements.txt
            pip install -r Pipfile
      - run:
          name: run tests
          command: |
            python ./workoutshare/manage.py test
      - run:
          name: run lint
          command: pipenv run "pylint .\workoutshare\"
