version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: workoutshare_admin
    executor: python/default
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: '--dev'
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run pytest 
          name: Test
      - run:
          command: |
            pipenv run pylint ./workoutshare
          name: Lint
workflows:
  main:
    jobs:
      - build
